spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/order
        - id: discovery-client
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/spring-boot-ms
server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

    instance:
      instance-id: ${spring.application.name}:${random.uuid}

logging:
  level:
    root: info
    org:
      springframework:
        cloud:
          gateway:
            route:
              RouteDefinitionLocator: TRACE



