spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/product-service
springdoc:
  swagger-ui:
    operations-sorter: method

server:
  port: 8080
