spring:
  application:
    name: inverntory-service
  datasource:
    url: jdbc:mysql://localhost:3306/inventory_service
    username: root
    password: toor

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
server:
  port: 8082
springdoc:
  swagger-ui:
    operations-sorter: method
